import Vue from 'vue'
import {
  Checkbox,
  CheckboxButton,
  CheckboxGroup,
  Switch,
  Select,
  Option,
  OptionGroup,
  Button,
  ButtonGroup,
  Row,
  Col,
  Progress,
  Input,
  InputNumber,
  Radio,
  ColorPicker,
  Form,
  FormItem,
  Tabs,
  TabPane,
  Tag,
  Slider
} from 'element-ui'
Vue.use(Checkbox)
Vue.use(CheckboxButton)
Vue.use(CheckboxGroup)
Vue.use(Switch)
Vue.use(Select)
Vue.use(Option)
Vue.use(OptionGroup)
Vue.use(Button)
Vue.use(ButtonGroup)
Vue.use(Row)
Vue.use(Col)
Vue.use(Progress)
Vue.use(Input)
Vue.use(InputNumber)
Vue.use(Radio)
Vue.use(ColorPicker)
Vue.use(Form)
Vue.use(FormItem)
Vue.use(Tabs)
Vue.use(TabPane)
Vue.use(Tag)
Vue.use(Slider)